/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'isService' : boolean,
  'itemId' : string,
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface CctvProduct {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface CctvService {
  'id' : bigint,
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface CommunityPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'replies' : Array<Reply>,
}
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'read' : boolean,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'paymentIntent' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export interface OrderItem {
  'id' : bigint,
  'isService' : boolean,
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Reply {
  'id' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'authorName' : string,
}
export interface ServiceBooking {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'scheduledDate' : bigint,
  'userId' : Principal,
  'email' : string,
  'address' : string,
  'notes' : string,
  'serviceId' : string,
  'phone' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'addProduct' : ActorMethod<[CctvProduct], undefined>,
  'addReply' : ActorMethod<[bigint, Reply], undefined>,
  'addService' : ActorMethod<[CctvService], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookService' : ActorMethod<[ServiceBooking], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCommunityPost' : ActorMethod<[CommunityPost], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<ServiceBooking>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCartItems' : ActorMethod<[], Array<CartItem>>,
  'getCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getProducts' : ActorMethod<[], Array<CctvProduct>>,
  'getServices' : ActorMethod<[], Array<CctvService>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserBookings' : ActorMethod<[Principal], Array<ServiceBooking>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[bigint], undefined>,
  'placeOrder' : ActorMethod<[Array<CartItem>, string], Order>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingStatus' : ActorMethod<[bigint, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<[CctvProduct], undefined>,
  'updateService' : ActorMethod<[CctvService], undefined>,
  'upgradeToPremium' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];